---
## Playbook to configure the Asterisk service to run as asterisk user.
# This playbook must be run after the asterisk.yml playbook.

# Create the asterisk user
- name: create '{{ user_asterisk }}' user
  user: name='{{ user_asterisk }}' createhome=no
  tags: asterisk
  
# Add asterisk user to admin group
- name: edit '{{ user_asterisk }}' group
  user: name='{{ user_asterisk }}' groups='{{ global_asterisk_group }}' force=yes append=yes
  when: global_asterisk_group is defined
  tags: asterisk

# Edit the asterisk configuration
- name: change asterisk process permissions
  lineinfile: dest='{{ dir_asterisk_config }}/asterisk.conf' regexp='^{{ item.original }}' line='{{ item.replacement }}'
  with_items:
    - { original: ';runuser', replacement: 'runuser = {{ user_asterisk }}' }
    - { original: ';rungroup', replacement: 'rungroup = {{ group_asterisk }}' }
    - { original: '\[directories\]', replacement: '[directories]' }
    - { original: 'astlogdir', replacement: 'astlogdir => {{ dir_asterisk_log }}' }
    - { original: ';[files]', replacement: '[files]' }
    - { original: ';astctlpermissions', replacement: 'astctlpermissions = 0670' }
    - { original: ';astctlowner', replacement: 'astctlowner = {{ user_asterisk }}' }
    - { original: ';astctlgroup', replacement: 'astctlgroup = {{ group_asterisk }}' }
  notify:
    - restart asterisk
  tags: asterisk

# Change ownership of Asterisk files
- name: change asterisk library permissions
  file: path='{{ item }}' owner='{{ user_asterisk }}' group='{{ user_asterisk }}' force=yes recurse=yes state=directory
  with_items:
    - /usr/lib/asterisk
    - /usr/include/asterisk
    - /dev/dahdi
    - /var/lib/asterisk
    - /var/spool/asterisk
  tags: asterisk

# Change ownership of Asterisk binaries
- name: change asterisk binary permissions
  file: path='{{ item }}' owner='{{ user_asterisk }}' group='{{ user_asterisk }}' force=yes
  with_items:
    - /usr/sbin/asterisk
    - /usr/include/asterisk.h
    - /usr/share/man/man8/asterisk.8
  tags: asterisk
  
# Change ownership of Asterisk configuration and logging files
- name: change asterisk configuration permissions
  file: path='{{ item }}' owner='{{ user_asterisk }}' group='{{ group_asterisk }}' state=directory recurse=yes force=yes mode=2775
  with_items:
    - '{{ dir_asterisk_config }}'
    - '{{ dir_asterisk_log }}'
  notify:
    - restart asterisk
  tags: asterisk