---
# ASTERISK-SPECIFIC BUILD TASKS
  
# Install Asterisk
- name: install Asterisk
  apt: >-
    pkg=asterisk
    state=latest
  tags: asterisk

# Install Asterisk core sound
- name: install Asterisk core sounds
  apt: >-
    pkg=asterisk-core-sounds-en*
    state=latest
  tags: asterisk

# Install Asterisk mp3
- name: install Asterisk
  apt: >-
    pkg=asterisk-mp3
    state=latest
  tags: asterisk
