---
## Configuration playbook to configure the Dahdi installation.
# This Playbook should be run after the asterisk.yml file, as it edits the chan_dahdi.conf file.

- name: create dummy configuration directory
  file: dest='/etc/asterisk' state=directory
  tags:
    - asterisk
    - dahdi_configuration
    
- name: create dummy configuration files
  copy: dest='{{ item }}' content=''
  with_items:
    - '{{ file_dahdi_channels }}'
    - '{{ file_dahdi_custom }}'
  tags:
    - asterisk
    - dahdi_configuration

# Assign Australia as the default zone
- name: update dahdi zone data
  lineinfile: 
    dest='/etc/dahdi/genconf_parameters'
    regexp='(?:^|[ /s#])lc_country(?:[ /s]|$)'
    line='lc_country    au'
  tags:
    - asterisk
    - dahdi_configuration

 # Generate the dahdi configuration file
- name: generate configuration file
  shell: '/usr/sbin/dahdi_genconf'
  tags:
    - asterisk
    - dahdi_configuration

- name: include the dahdi configuration files
  template:
    dest='{{ file_dahdi_channel }}'
    src='chan_dahdi.conf'
    owner='{{ user_asterisk }}'
  tags:
    - asterisk
    - dahdi_configuration