---
# DAHDI-SPECIFIC BUILD FILE

# Fetch the dahdi drivers
- name: get dahdi source code
  get_url: url=$url_dahdi dest=$dir_asterisk_source/$tar_dahdi
  tags: dahdi
  
# Unzip dahdi drivers
- name: unzip dahdi source
  command: /bin/tar xf $dir_asterisk_source/$tar_dahdi -C $dir_asterisk_source
  tags: dahdi
  
# Build dahdi drivers
- name: build dahdi drivers
  command: /usr/bin/make chdir=$dir_asterisk_source/$dir_dahdi
  tags: dahdi
  
# Install dahdi drivers
- name: build install drivers
  command: /usr/bin/make install chdir=$dir_asterisk_source/$dir_dahdi
  tags: dahdi
  
# Configure dahdi drivers
- name: configure drivers
  command: /usr/bin/make config chdir=$dir_asterisk_source/$dir_dahdi
  tags: dahdi
  
# Correct the dahdi user
- name: assign dahdi to $uname
  command: /bin/sed -i "s/{{ item.original }}/{{ item.replacement }}/g" /etc/udev/rules.d/dahdi.rules
  with_items:
    - { original: \"asterisk\", replacement: \"$uname\" }
  tags: dahdi
  
# Load dahdi hardware
- name: load dahdi
  service: name=dahdi state=started
  tags: dahdi