---
# DAHDI-SPECIFIC BUILD FILE

- name: install dahdi
  install: url='{{ url_dahdi }}' dest='{{ dir_asterisk_source }}'
  tags:
    - asterisk
    - dahdi
  
# Configure dahdi drivers
- name: configure dahdi
  command: /usr/bin/make config chdir='{{ dir_asterisk_source }}/{{ dir_dahdi }}'
  tags:
    - asterisk
    - dahdi
  
# Load dahdi hardware
- name: load dahdi
  service: name=dahdi state=started
  when: global_debug == True
  tags:
    - asterisk
    - dahdi
