---
# ASTERISK INSTALLATION PLAYBOOK
# This should be run after the USER playbook

######### Pre-game

# Create the logging directory if the default is not being used.
- name: create logging directory
  file: path='{{ dir_asterisk_log }}' state=directory mode=2775
  when: global_log_dir is defined
  tags: 
    - asterisk
    - build

######### Showtime!

- include: dahdi.yml
- include: dahdi_configuration.yml
- include: asterisk.yml
- include: asterisk_configuration.yml
  
######## Post-game party.
