---
# ASTERISK INSTALLATION PLAYBOOK
# This should be run after the USER playbook

######### Pre-game

# Install required libraries
- name: install pre-installation libraries
  apt: pkg=$item state=latest force=yes
  with_items: $pre_install_libraries
  tags: asterisk
  
# Install linux-headers.
- name: install linux headers
  shell: apt-get install -y linux-headers-$(uname -r)
  tags: asterisk
  
# Create a source directory
- name: create source directory
  file: path=$dir_asterisk_source state=directory force=yes
  tags: asterisk

######### Showtime!

- include: dahdi.yml
- include: libpri.yml
- include: asterisk.yml
- include: asterisk_permission.yml
  
######## Post-game party.

# Cleanup the source directory
- name: remove source files
  file: path=$dir_asterisk_source state=absent recurse=yes force=yes
  ignore_errors: yes
  notify:
    - change $home directory permissions
  tags: asterisk
  
# Cleanup build packages
- name: remove build tools
  apt: pkg=$item state=absent purge=yes
  with_items:
    - make
    - zip
    - unzip
  ignore_errors: yes
  tags: asterisk